server:
  port: 9090
spring:
  datasource:
    url: jdbc:mysql://120.79.168.114:3307/test?useUnicode=true&autoReconnect=true&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 2MB
  cache:
    type: simple